on:
  push:
    branches: [ master ]
    
steps:
- uses: actions/checkout@v1
- uses: meteorengineer/setup-meteor@v1
  with:
    meteor-release: '1.8.1'
- run: meteor npm install
- run: meteor npm test
