on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        meteor: [ '1.8.1', '1.9-beta.3' ]
    name: Meteor ${{ matrix.meteor }} sample
    steps:
      - uses: actions/checkout@v1
      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v1.0.2
        with:
          meteor-release: ${{ matrix.meteor }}
      - run: meteor npm install
      - run: meteor npm test
