- name: Setup Meteor.js environment
  uses: meteorengineer/setup-meteor@v1.0.2

steps:
- uses: actions/checkout@v1
  with:
    meteor-release: '1.8.1'
- run: meteor npm install
- run: meteor npm test
